export const rosters: { [key: string]: { men: string[]; women: string[] } } = {
  "WWE RAW": {
    men: [
      "AJ Styles",
      "Akira Tozawa",
      "Austin Theory",
      "Bron Breakker",
      "Bronson Reed",
      "Brutus Creed",
      "Chad Gable (El Grande Americano)",
      "CM Punk",
      "Cruz Del Toro",
      "Dominik Mysterio (Intercontinental Champion)",
      "Dragon Lee",
      "Drew McIntyre",
      "Erik",
      "Finn Bálor",
      "Grayson Waller",
      "Gunther (World Heavyweight Champion)",
      "Ilja Dragunov (Injured)",
      "Ivar",
      "JD McDonagh",
      "Jey Uso",
      "Joaquin Wilde",
      "Julius Creed",
      "Karrion Kross",
      "Kofi Kingston (World Tag Team Champion)",
      "Logan Paul",
      "Ludwig Kaiser",
      "Otis",
      "Penta",
      "Pete Dunne",
      "Rey Mysterio (Injured)",
      "Ron Killings (R-Truth)",
      "Rusev",
      "Sami Zayn",
      "Seth Rollins (Money in the Bank contract holder)",
      "Sheamus",
      "Tyler Bate",
      "Xavier Woods (World Tag Team Champion)",
    ],
    women: [
      "Asuka",
      "Bayley",
      "Becky Lynch",
      "Ivy Nile",
      "Iyo Sky",
      "Kairi Sane",
      "Kiana James",
      "Liv Morgan",
      "Lyra Valkyria",
      "Maxxine Dupri",
      "Natalya",
      "Raquel Rodriguez",
      "Rhea Ripley",
      "Roxanne Perez",
      "Scarlett Bordeaux",
      "Stephanie Vaquer",
      "Zoey Stark",
    ],
  },
  "WWE SMACKDOWN": {
    men: [
        "Aleister Black",
        "Alex Shelley",
        "Andrade",
        "Angel Garza",
        "Angelo Dawkins",
        "Apollo Crews",
        "Axiom",
        "Bo Dallas / Uncle Howdy",
        "Carmelo Hayes",
        "Chris Sabin",
        "Cody Rhodes",
        "Damian Priest",
        "Dexter Lumis / Mercy the Buzzard",
        "Drew McIntyre",
        "Elton Prince",
        "Erick Rowan / Ramblin' Rabbit",
        "Humberto Carrillo",
        "Jacob Fatu",
        "Jimmy Uso",
        "Joe Gacy / Huskus The Pig Boy",
        "Johnny Gargano",
        "Kevin Owens",
        "Kit Wilson",
        "LA Knight",
        "The Miz",
        "Montez Ford",
        "Nathan Frazer",
        "Randy Orton",
        "Rey Fenix",
        "Roman Reigns",
        "Ron Killings (R-Truth)",
        "Santos Escobar",
        "Shinsuke Nakamura",
        "Solo Sikoa",
        "Tama Tonga",
        "Tonga Loa",
        "Tommaso Ciampa",
    ],
    women: [
        "Alba Fyre",
        "Alexa Bliss",
        "B-Fab",
        "Bianca Belair",
        "Candice LeRae",
        "Charlotte Flair",
        "Chelsea Green",
        "Giulia",
        "Jade Cargill",
        "Michin",
        "Naomi",
        "Nia Jax",
        "Nikki Cross / Abby the Witch",
        "Piper Niven",
        "Tiffany Stratton",
        "Zelina Vega",
    ],
  },
  "WWE NXT": {
      men: [
        "Andre Chase",
        "Ashante \"Thee\" Adonis",
        "Brooks Jensen",
        "Bronco Nima",
        "Channing \"Stacks\" Lorenzo",
        "Charlie Dempsey",
        "Cutler James",
        "Dante Chen",
        "Dion Lennox",
        "Ethan Page",
        "Hank Walker",
        "Kale Dixon",
        "Jasper Troy",
        "Je'Von Evans",
        "Josh Briggs",
        "Lexis King",
        "Luca Crusifino",
        "Lucien Price",
        "Malik Blade",
        "Myles Borne",
        "Niko Vance",
        "Noam Dar",
        "Oba Femi",
        "Osiris Griffin",
        "Ricky Saints",
        "Ridge Holland",
        "Saquon Shugars",
        "Shawn Spears",
        "Tank Ledger",
        "Tavion Heights",
        "Tony D'Angelo",
        "Trick Williams",
        "Tyriek Igwe",
        "Tyson DuPont",
        "Uriah Connors",
        "Wes Lee",
        "Yoshiki Inamura",
      ],
      women: [
        "Adriana Rizzo",
        "Arianna Grace",
        "Fallon Henley",
        "Izzi Dame",
        "Jacy Jayne",
        "Jaida Parker",
        "Jazmyn Nyx",
        "Jordynne Grace",
        "Karmen Petrovic",
        "Kelani Jordan",
        "Lash Legend",
        "Lola Vice",
        "Mariah May",
        "Nikkita Lyons",
        "Sol Ruca",
        "Tatum Paxley",
        "Thea Hail",
        "Tyra Mae Steele",
        "Wren Sinclair",
        "ZARIA",
      ],
  },
  "AEW": {
      men: [
        "Aaron Solo",
        "Action Andretti",
        "Adam Cole",
        "Adam Copeland",
        "\"Hangman\" Adam Page",
        "Alex Reynolds",
        "Angelico",
        "Angelo Parker",
        "Anthony Bowens",
        "Anthony Ogogo",
        "AR Fox",
        "Ari Daivari",
        "Austin Gunn",
        "Bandido",
        "The Beast Mortos",
        "Big Bill",
        "Billy Gunn",
        "Bishop Kaun",
        "The Blade",
        "Bobby Lashley",
        "Brandon Cutler",
        "Brian Cage",
        "Brody King",
        "Bryan Danielson",
        "Bryan Keith",
        "Buddy Matthews",
        "The Butcher",
        "Cash Wheeler",
        "Chris Jericho",
        "Christian Cage",
        "Christopher Daniels",
        "Chuck Taylor",
        "Claudio Castagnoli",
        "Cole Karter",
        "Colt Cabana",
        "Colten Gunn",
        "Dalton Castle",
        "Danhausen",
        "Daniel Garcia",
        "Dante Martin",
        "Darby Allin",
        "Darius Martin",
        "Dax Harwood",
        "Dralístico",
        "Dustin Rhodes",
        "Eddie Kingston",
        "Evil Uno",
        "Griff Garrison",
        "Hologram",
        "Hook",
        "Isiah Kassidy",
        "Jack Perry",
        "Jay Lethal",
        "Jay White",
        "JD Drake",
        "Jeff Jarrett",
        "John Silver",
        "Johnny TV",
        "Jon Moxley",
        "Josh Woods",
        "Juice Robinson",
        "Kazuchika Okada",
        "Keith Lee",
        "Kenny Omega",
        "Kris Statlander",
        "Lance Archer",
        "Luchasaurus",
        "Malakai Black",
        "Matt Jackson",
        "Matt Hardy",
        "Matt Sydal",
        "Maxwell Jacob Friedman (MJF)",
        "Nick Jackson",
        "Orange Cassidy",
        "Pac",
        "Preston Vance",
        "Penta El Zero M",
        "Rey Fenix",
        "Ricky Starks",
        "Rush",
        "Sammy Guevara",
        "Santana",
        "Scorpio Sky",
        "Shawn Spears",
        "Swerve Strickland",
        "Tony Nese",
        "Trent Beretta",
        "Wardlow",
        "Wheeler Yuta",
        "Will Ospreay",
      ],
      women: [
        "Anna Jay",
        "Athena",
        "Ava",
        "Billie Starkz",
        "Big Swole",
        "Britt Baker",
        "Dani Jordyn",
        "Emi Sakura",
        "Hikaru Shida",
        "Jade Cargill",
        "Jamie Hayter",
        "Julia Hart",
        "Kris Statlander",
        "Leyla Hirsch",
        "Madison Rayne",
        "Nyla Rose",
        "Penelope Ford",
        "Red Velvet",
        "Riho",
        "Ruby Soho",
        "Saraya",
        "Serena Deeb",
        "Skye Blue",
        "Tay Conti",
        "Thunder Rosa",
        "Toni Storm",
        "Willow Nightingale",
      ],
  },
  "ROH": {
      men: [
        "Angélico",
        "Anthony Henry",
        "Atlantis Jr.",
        "Austin Gunn",
        "Bandido (ROH World Champion)",
        "Bishop Kaun",
        "Blake Christian",
        "Brian Cage",
        "Carlie Bravo",
        "Claudio Castagnoli",
        "Cole Karter",
        "Colten Gunn",
        "Dalton Castle",
        "Daniel Garcia",
        "Dante Martin",
        "Darius Martin",
        "Dustin Rhodes (ROH World Six-Man Tag Team Champion, World Tag Team Champion)",
        "Eddie Kingston (currently inactive due to leg injury)",
        "Griff Garrison",
        "Jacked Jameson",
        "Jay White",
        "JD Drake",
        "Johnny TV (John Morrison)",
        "Katsuyori Shibata",
        "Komander (ROH World Television Champion)",
        "Kyle Fletcher",
        "Lee Johnson",
        "Lee Moriarty (ROH Pure Champion)",
        "Mansoor",
        "Mark Briscoe (Hall of Famer)",
        "Marshall Von Erich (ROH World Six-Man Tag Team Champion)",
        "Mason Madden",
        "Matt Taven",
        "Mike Bennett",
        "Nick Wayne (ROH World Television Champion)",
        "Ross Von Erich (ROH World Six-Man Tag Team Champion)",
        "Sammy Guevara (ROH World Tag Team Champion)",
        "Shane Taylor",
        "Shawn Dean",
        "Toa Liona",
        "Tony Nese",
        "Wheeler Yuta",
      ],
      women: [
        "Athena (ROH Women's World Champion)",
        "Billie Starkz",
        "Charlette Renegade",
        "Deonna Purrazzo",
        "Diamante",
        "Lady Frost",
        "Leila Grey",
        "Marina Shafir",
        "Mercedes Martinez",
        "Queen Aminata",
        "Rachael Ellering",
        "Red Velvet (ROH Women's World Television Champion)",
        "Robyn Renegade",
        "Serena Deeb",
        "Taya Valkyrie",
        "Trish Adora",
      ],
  },
  "TNA": {
      men: [
        "Ace Steel",
        "A.J. Francis",
        "Brian Myers",
        "Chris Bey",
        "Eddie Edwards",
        "Elijah",
        "Eric Young",
        "Frankie Kazarian",
        "Harley Hudson",
        "Jake Something",
        "Jason Hotch",
        "Jeff Hardy",
        "JDC",
        "Joe Hendry",
        "John Skyler",
        "Judas Icarus",
        "KC Navarro",
        "Laredo",
        "Leon Slater",
        "Mance Warner",
        "Matt Cardona",
        "Matt Hardy",
        "Matthew Rehwoldt",
        "Mike Santana",
        "Moose (TNA X Division Champion)",
        "Mustafa Ali",
        "Nic Nemeth (TNA World Tag Team Champion)",
        "Octagón Jr.",
        "Ryan Nemeth (TNA World Tag Team Champion)",
        "Sami Callihan (Director of Live Events)",
        "Santino Marella",
        "Steve Maclin (TNA International Champion)",
        "Tommy Dreamer",
        "Trey Miguel",
        "Trick Williams (TNA World Champion; appears via NXT partnership)",
        "Zachary Wentz",
      ],
      women: [
        "Alisha Edwards",
        "Ash By Elegance (TNA Knockouts World Tag Team Champion)",
        "Cassie Lee",
        "Dani Luna",
        "Harley Hudson",
        "Heather By Elegance (TNA Knockouts World Tag Team Champion)",
        "Indi Hartwell",
        "Jody Threat",
        "Killer Kelly",
        "KiLynn King",
        "Lei Ying Lee",
        "M By Elegance",
        "Masha Slamovich (TNA Knockouts World Champion)",
        "Mila Moore",
        "Myla Grace",
        "Rosemary",
        "Steph De Lander",
        "Tasha Steelz",
        "Tessa Blanchard",
        "Victoria Crawford",
        "Xia Brookside",
      ],
  },
  "MLW": {
      men: [
        "Alex Kane",
        "Alex Hammerstone",
        "Akira",
        "Bad Dude Tito",
        "Calvin Tankman",
        "Davey Boy Smith Jr.",
        "Jacob Fatu",
        "Juicy Finau",
        "Lance Anoa’i",
        "Mads Krügger",
        "Matthew Justice",
        "Mr. Thomas",
        "O’Shay Edwards",
        "Rickey Shane Page",
        "Sam Adonis",
        "Sami Callihan",
        "Tom Lawlor",
        "Timothy Thatcher",
        "TJ Perkins",
        "1 Called Manders",
        "Rocky Romero",
        "Matt Cardona",
        "Richard Holliday",
        "Jimmy Lloyd",
        "Kevin Blackwood",
        "Danny Limelight",
        "Myron Reed",
        "Delmi Exo",
        "Ichiban",
        "Shigehiro Irie",
        "Willie Mack",
        "YAMATO",
      ],
      women: [
        "B3CCA",
        "Delmi Exo (MLW World Women’s Featherweight Champion)",
        "Janai Kai",
        "Maki Itoh",
        "Mandy León",
        "Nicole Savoy",
        "Taya Valkyrie",
        "Zayda Steel",
      ],
  },
  "GCW": {
      men: [
        "Alec Price",
        "Alex Zayne",
        "Andrew Everett",
        "Atticus Cogar",
        "Bandido",
        "Blake Christian",
        "Brody King",
        "Chris Dickinson",
        "Chris Jericho (part-time)",
        "Danhausen",
        "Effy (GCW World Champion)",
        "Flip Gordon",
        "Homicide",
        "Jack Cartwheel",
        "Jack Perry",
        "Jacob Vadocq",
        "Jada Stone",
        "Jake Atlas",
        "Jake Something",
        "Jeff Hardy",
        "Joey Janela",
        "John Wayne Murdoch",
        "Josh Bishop",
        "Josh Briggs",
        "Josh Alexander",
        "Josh Woods",
        "Juice Robinson",
        "Karrion Kross",
        "Kevin Ku",
        "Lee Moriarty",
        "Lio Rush",
        "Mance Warner",
        "Matt Tremont (GCW Ultraviolent Champion)",
        "Matt Hardy",
        "Matt Riddle",
        "Maxwell Jacob Friedman (MJF) (part-time)",
        "Mike Bailey",
        "Mike Santana",
        "Minoru Suzuki",
        "Nate Webb",
        "Nick Gage",
        "Orange Cassidy (part-time)",
        "PCO",
        "Ricky Morton",
        "Ricky Starks",
        "Rina Yamashita",
        "Sammy Guevara (part-time)",
        "Shane Taylor",
        "Tony Deppen",
        "Trent Beretta",
        "W. Morrissey",
        "Zachary Wentz",
      ],
      women: [
        "Abadon",
        "Alex Gracia",
        "Allie Katch",
        "Billie Starkz",
        "Brody King",
        "Effy",
        "Hikari Noa",
        "Hollyhood Haley",
        "Jamie Senegal",
        "Jordynne Grace",
        "Kasey Catal",
        "Kelsey Rae",
        "Kylie Rae",
        "Maki Itoh",
        "Max The Impaler",
        "Nicole Savoy",
        "Penelope Ford",
        "Rina Yamashita",
        "Scarlett Bordeaux",
        "Shayna Baszler (part-time)",
        "Skye Blue",
        "Taya Valkyrie",
        "Toni Storm (part-time)",
        "Willow Nightingale",
      ],
  },
  "REVOLVER": {
      men: [
        "Ace Austin",
        "Alex Colon",
        "Damian Chambers",
        "Myron Reed",
        "Jake Crist",
        "Jake Something",
        "RED",
        "Matthew Palmer",
        "Mike Bailey",
        "Brent Oakley",
        "Rickey Shane Page",
        "Steve Maclin",
        "Alex Shelley",
        "Crash Jaxon",
        "Gringo Loco",
        "KC Jacobs",
        "Lince Dorado",
        "Rich Swann",
        "1 Called Manders",
        "Fulton",
        "Trey Miguel",
        "Zachary Wentz",
        "Alpha Sigma Sigma",
        "Dark Pledge",
        "Grizzled Young Veterans (James Drake & Zack Gibson)",
        "Mance Warner",
        "Matthew Justice",
        "Ryan Matthias",
        "Atticus Cogar",
        "Brayden Lee",
        "Dub Club",
        "Crew",
        "Davey Bang",
        "Elijah",
        "JD Griffey",
        "JJ Garrett",
        "JT Dunn",
        "Krule",
        "Ninja Mack",
        "Moose",
        "Marcus Mathers",
        "Calvin Tankman",
        "Mustafa Ali",
        "August Matthews",
        "Joe Alonzo",
        "Koda Hernandez",
        "Sabin Gauge",
        "KJ Reynolds",
        "Ryan Matthias",
        "DreadKNOT",
        "Alan Angels",
        "BDE",
        "Crash",
        "Dante Leon",
        "Jeffrey John",
        "Juni Underwood",
        "Bigg Pound",
        "Sam Stackhouse",
        "Sam Beale",
        "Sam Adonis",
        "Judge Joe Dred",
        "KC Navarro",
        "Matt Makowski",
        "Mike Santana",
        "Mansoor",
        "Rhino",
        "Rohit Raju",
        "Sami Callihan",
        "Tony Deppen",
        "Willie Mack",
      ],
      women: [
        "Jessicka Havok",
        "Priscilla Kelly (fka Gigi Dolin)",
        "Killer Kelly",
        "Marina Shafir",
        "Jody Threat",
        "Rachel Armstrong",
        "Kayla Kassidy",
        "Hyan",
        "Kat Carter",
      ],
  },
  "DPW": {
      men: [
        "Adam Priest (DPW World Champion)",
        "Andrew Everett",
        "Anthony Henry",
        "Bryan Keith",
        "Calvin Tankman",
        "Channing Thomas",
        "Chris Danger",
        "Colby Corino",
        "Diego Hill",
        "Dominic Garrini",
        "Dustin Waller",
        "Grizzled Young Veterans (James Drake & Zack Gibson, DPW Tag Team Champions)",
        "Ichiban",
        "Jake Something",
        "Jay Malachi",
        "JD Drake",
        "Juni Underwood",
        "Kevin Blackwood",
        "Kevin Ku",
        "Kylon King",
        "LaBron Kozone (DPW National Champion)",
        "Landon Hale",
        "Love Doug",
        "Luther",
        "Mike Bailey",
        "Miracle Generation (Dustin Waller & Kylon King)",
        "Myron Reed",
        "Starboy Charlie",
        "Titus Alexander",
        "Tom Lawlor",
        "Trevor Lee",
        "1 Called Manders",
        "BK Westbrook",
      ],
      women: [
        "Dani Luna (DPW Women’s World Champion)",
        "Emi Sakura",
        "Kylie Rae",
        "Miyuki Takase",
        "Nicole Matthews",
        "Queen Aminata",
        "Rosemary",
      ],
  },
  "Smash": {
      men: [
        "Psycho Mike (Smash Wrestling Champion)",
        "Mark Wheeler (2025 Northern Tournament winner, #1 Contender)",
        "Carter Mason",
        "London Lightning",
        "Jonny Deluca",
        "Jax Williams",
        "Brent Banks",
        "Stu Grayson",
        "Jason Hotch",
        "Vaughn Vertigo",
        "Jimmy Townsend",
        "Tarik",
        "Kingsley",
        "Judas Icarus (Smash Tag Team Champion)",
        "Travis Williams (Smash Tag Team Champion)",
        "Josh Alexander",
        "Matt Tremont",
        "Mike Bailey",
        "Matt Makowski",
        "Mike Bailey",
        "Davey Vega",
        "Jake Something",
        "Matt Cardona",
        "Rhino",
        "Rich Swann",
        "Sami Callihan",
        "Tony Deppen",
        "Willie Mack",
      ],
      women: [
        "Masha Slamovich",
        "Jody Threat (Smash Women’s Champion)",
        "Allie Katch",
        "Billie Starkz",
        "Jamie Senegal",
        "Kasey Catal",
        "Kayla Kassidy",
        "Killer Kelly",
        "Marina Shafir",
        "Nicole Savoy",
        "Penelope Ford",
        "Rachel Ellering",
        "Scarlett Bordeaux",
        "Shayna Baszler",
        "Skye Blue",
        "Taya Valkyrie",
        "Toni Storm",
        "Willow Nightingale",
      ],
  },
  "Rock Solid": {
      men: [
        "John Atlas",
        "Scotty the Body",
        "Rex Atkins",
        "Asylum",
        "Andrew Davis",
        "Bang Bang Pete",
        "Cody Deaner",
        "Jake O’Reilly",
        "Jim Nye",
        "Kwan Chang",
        "Lionel Knight",
        "RJ City",
        "Sebastian Suave",
        "Tyler Tirva",
        "The Brooklyn Foot",
        "The Hacker",
        "The Latin Sensation",
        "Tornado",
        "Tyson Dux",
        "Will White",
      ],
      women: [
        "Beautiful Beaa",
        "Jody Threat",
        "Kaitlin Diemond",
        "Nova",
        "Seleziya Sparx",
      ],
  },
};